[window]
opacity = 1.0
padding.x = 4
padding.y = 4
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "JetBrains Mono"
bold.family = "JetBrains Mono"
size = 9
offset.x = 0
offset.y = 4
glyph_offset.y = 4

[cursor]
style = { shape = "block" }

