[window]
opacity = 1.0
padding.x = 4
padding.y = 4
decorations = "Full"
decorations_theme_variant = "Light"

[font]
normal.family = "Fira Code Retina"
bold.family = "Fira Code Retina"
size = 10
offset.x = 0
offset.y = 10
glyph_offset.y = 5

[cursor]
style = { shape = "block" }

[colors.primary]
background = "#edeeeb"
foreground = "#2a2c33"

[colors.cursor]
cursor = "#bbbbbb"

[colors.normal]
black = "#000000"
red = "#de3e35"
green = "#3f953a"
yellow = "#d2b67c"
blue = "#2f5af3"
magenta = "#950095"
cyan = "#3f953a"
white = "#dfe1dc"

[colors.bright]
black = "#000000"
red = "#de3e35"
green = "#3f953a"
yellow = "#d2b67c"
blue = "#2f5af3"
magenta = "#950095"
cyan = "#3f953a"
white = "#ffffff"
