[window]
opacity = 1.0
padding.x = 4
padding.y = 4
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "Cascadia Code"
bold.family = "Cascadia Code"
size = 8
offset.x = 0
offset.y = 2
glyph_offset.y = 2

[cursor]
style = { shape = "block" }

