[window]
opacity = 1.0
padding.x = 4
padding.y = 4
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "JetBrains Mono"
bold.family = "JetBrains Mono"
size = 12
offset.x = 0
offset.y = 4
glyph_offset.y = 4

[cursor]
style = { shape = "block" }

[colors.primary]
background = "#232627"
foreground = "#b3b1ad"

[colors.cursor]
cursor = "#b3b1ad"

[colors.normal]
black = "#232627"
red = "#ed1515"
green = "#11d116"
yellow = "#f67400"
blue = "#1d99f3"
magenta = "#9b59b6"
cyan = "#1abc9c"
white = "#fcfcfc"

[colors.bright]
black = "#565a5b"
red = "#ed1515"
green = "#11d116"
yellow = "#f67400"
blue = "#1d99f3"
magenta = "#9b59b6"
cyan = "#1abc9c"
white = "#fcfcfc"
