[system_packages]
base_packages = [
    "kakoune",
    "make",
    "cmake",
    "network-manager",
    "net-tools",
    "bwm-ng",
    "tty-clock",
    "jq",
    "curl",
    "axel",
    "wget",
    "zip",
    "dtrx",
    "git",
    "htop",
    "redshift",
    "dfc",
    "mtr",
    "tmux",
    "xterm",
    "acpi",
    "lm-sensors",
    "p7zip",
    "fonts-jetbrains-mono",
    "fonts-roboto",
    "fonts-firacode",
    "zoxide",
    "pkg-config",
    "rsync",
    "scrot",
]

common_apps = [
    "chromium",
    "gimp",
    "transmission-qt",
    "mpv",
    "gparted",
    "bleachbit",
    "synaptic",
]

[flatpak]
packages = [
	"org.chromium.Chromium",
    "com.bitwarden.desktop",
    #"md.obsidian.Obsidian",
    "io.beekeeperstudio.Studio",
    "com.github.alecaddd.sequeler",
    #"com.usebruno.Bruno"
]

[vscode]
version = "1.107.18627"

[docker]
system_packages = [
    "docker.io",
]

[go]
version = "1.25.5"
packages = [
    "golang.org/x/tools/gopls@latest",
    "github.com/go-delve/delve/cmd/dlv@latest",
    "github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest",
    "github.com/nametake/golangci-lint-langserver@latest",
]

[nodejs]
version = "25"
global_deps = ["npm", "typescript-language-server"]

[python]
system_packages = ["python3-pip", "python3-venv", "pipx"]
pip_packages = ["pyright", "ruff", "mypy"]

[java]
system_packages = ["openjdk-21-jdk", "maven"]

[xorg]
system_packages = [
    "cwm",
    "hsetroot",
    "lxappearance",
    "alacritty",
    "thunar",
    "imv",
    "viewnior",
    "i3lock",
    "picom",
    "dmenu",
    "mousepad",
    "gnome-themes-extra",
    "libssl-dev",
    "libxrandr-dev",
    "libxinerama-dev",
    "libxcursor-dev",
    "libxi-dev",
    "libopengl-dev",
    "libgl1-mesa-dev",
]
