[system_packages]
base_packages = [
    "kakoune",
    "make",
    "cmake",
    "network-manager",
    "net-tools",
    "bwm-ng",
    "tty-clock",
    "jq",
    "dzen2",
    "curl",
    "axel",
    "wget",
    "zip",
    "dtrx",
    "git",
    "htop",
    "redshift",
    "dfc",
    "tmux",
    "xterm",
    "acpi",
    "lm-sensors",
    "p7zip",
    "fonts-jetbrains-mono",
    "fonts-roboto",
    "fonts-cascadia-code",
    "gnome-themes-extra",
    "tango-icon-theme",
    "tango-icon-theme-common",
    "tango-icon-theme-extras",
    "zoxide",
    "pkg-config",
    "rsync",
    "scrot",
]

common_apps = [
    "gimp",
    "transmission-gtk",
    "mpv",
    "gparted",
    "bleachbit",
]


[docker]
system_packages = [
    "docker.io",
    "docker-compose",
    "docker-buildx"
]


[java]
system_packages = ["openjdk-21-jdk", "maven"]


[flatpak]
system_packages = ["flatpak"]
packages = [
    "org.chromium.Chromium",
    "com.bitwarden.desktop",
    "md.obsidian.Obsidian",
    "io.beekeeperstudio.Studio",
    "com.github.alecaddd.sequeler",
    "com.usebruno.Bruno",
    "com.simplenote.Simplenote",
]


[nodejs]
version = 25
global_deps = ["npm", "typescript-language-server"]


[cpp]
llvm_version = 19
gcc_version = 14
packages = [
    "llvm-[llvm_version]",
    "clang",
    "clangd",
    "clang-format",
    "clang-[llvm_version]",
    "clangd-[llvm_version]",
    "clang-format-[llvm_version]",
    "gcc-[gcc_version]",
    "g++-[gcc_version]",
    "bear",
    "cmake",
    "valgrind"
]


[python]
system_packages = ["python3-pip", "python3-venv", "pipx"]
pip_packages = ["pyright", "ruff", "mypy"]


[xorg]
system_packages = [
    "cwm",
    "hsetroot",
    "lxappearance",
    "alacritty",
    "thunar",
    "imv",
    "viewnior",
    "i3lock",
    "picom",
    "dzen2",
    "dmenu",
    "mousepad"
]
