base_packages = [
    "openssh-server",
    "kakoune",
    "flatpak",
    "make",
    "cmake",
    "net-tools",
    "bwm-ng",
    "tty-clock",
    "jq",
    "curl",
    "axel",
    "wget",
    "zip",
    "dtrx",
    "gparted",
    "git",
    "htop",
    "redshift",
    "dfc",
    "tmux",
    "xterm",
    "acpi",
    "lm-sensors",
    "p7zip",
    "fonts-jetbrains-mono",
    "fonts-roboto",
    "gnome-themes-extra",
    "mpv",
    "zoxide",
    "pkg-config",
    "rsync",
    "imv",
    "nwg-look",
    "gimp"
]

flatpak_packages = [
    "org.chromium.Chromium",
    "com.bitwarden.desktop",
    "md.obsidian.Obsidian",
    "io.beekeeperstudio.Studio",
    "com.usebruno.Bruno",
    "com.simplenote.Simplenote",
]