[packages]
base = [
    "openssh-server",
    "kakoune",
    "flatpak",
    "make",
    "cmake",
    "network-manager",
    "net-tools",
    "libgdk-pixbuf-2.0-dev",
    "bwm-ng",
    "tty-clock",
    "jq",
    "curl",
    "axel",
    "wget",
    "zip",
    "dtrx",
    "gparted",
    "git",
    "htop",
    "redshift",
    "dfc",
    "tmux",
    "xterm",
    "acpi",
    "lm-sensors",
    "hsetroot",
    "p7zip",
    "fonts-jetbrains-mono",
    "fonts-roboto",
    "fonts-cascadia-code",
    "gnome-themes-extra",
    "mpv",
    "zoxide",
    "pkg-config",
    "rsync",
    "imv",
    "nwg-look",
    "gimp"
]

flatpak = [
    "org.chromium.Chromium",
    "com.bitwarden.desktop",
    "md.obsidian.Obsidian",
    "io.beekeeperstudio.Studio",
    "com.github.alecaddd.sequeler",
    "com.usebruno.Bruno",
    "com.simplenote.Simplenote",
]

docker = [
    "docker.io",
    "docker-compose",
]

cpp = [
    "llvm-19",
    "clang",
    "clangd",
    "clang-format",
    "clang-19",
    "clangd-19",
    "clang-format-19",
    "gcc-14",
    "g++-14",
    "bear",
    "cmake",
    "valgrind"    
]

python = [
    "python3-pip",
    "python3-venv",
    "pipx",
]

pip = [
    "pyright",
    "ruff",
    "mypy",
]

java = [
    "openjdk-21-jdk",
    "maven",
]

cwm = [
    "yaru-theme-icon",
    "yaru-theme-gtk",
    "cwm",
    "lxappearance",
    "alacritty",
    "thunar",
    "viewnior",
    "i3lock",
    "gmrun",
    "picom",
    "dzen2",
    "mousepad",
    "nwg-look",
]
